language: node_js

services:
  - docker

before_script:
  - docker build -t ikethecoder/gitlab-keycloak-group-sync .

deploy:
  provider: script
  script: bash docker_push
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"  
