language: node_js

services:
  - docker

jobs:
  include:
    - stage: deploy
      install:
      - docker build -t ikethecoder/gitlab-keycloak-group-sync .
      provider: script
      script: bash docker_push
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"  
