language: node_js

services:
  - docker

script:
  - docker build -t ikethecoder/gitlab-keycloak-group-sync .

jobs:
  include:
    - stage: deploy
      install: skip # bundle install is not required
      provider: script
      script: bash docker_push
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"  
