#!/bin/bash

export REPO="gitlab-keycloak-group-sync"

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker push ikethecoder/$REPO:latest
docker push ikethecoder/$REPO:$TRAVIS_COMMIT

if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    echo "dockerfile tagged pushing now"
    docker push ikethecoder/$REPO:$TRAVIS_TAG
    echo "$TRAVIS_TAG pushed successfully"
fi
